# Generated by Django 6.0.1 on 2026-01-26 02:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('rg', models.CharField(blank=True, max_length=30, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino')], max_length=15, null=True)),
                ('entrada_ilpi', models.DateField(blank=True, null=True)),
                ('quarto', models.CharField(blank=True, max_length=20, null=True)),
                ('leito', models.CharField(blank=True, max_length=20, null=True)),
                ('contato_emergencia', models.CharField(blank=True, max_length=200, null=True)),
                ('telefone_emergencia', models.CharField(blank=True, max_length=30, null=True)),
                ('alergias', models.TextField(blank=True, null=True)),
                ('condicoes_cronicas', models.TextField(blank=True, null=True)),
                ('grau_dependencia', models.IntegerField(default=1)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=30)),
                ('modulo', models.CharField(max_length=60)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('detalhes', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('tipo_ocorrencia', models.CharField(max_length=80)),
                ('descricao', models.TextField()),
                ('conduta', models.TextField(blank=True, null=True)),
                ('gravidade', models.CharField(blank=True, max_length=20, null=True)),
                ('resolvido', models.BooleanField(default=False)),
                ('data_resolucao', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='core.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_medicamento', models.CharField(max_length=200)),
                ('dosagem', models.CharField(blank=True, max_length=100, null=True)),
                ('via_administracao', models.CharField(blank=True, max_length=60, null=True)),
                ('frequencia', models.CharField(blank=True, max_length=60, null=True)),
                ('horarios', models.CharField(blank=True, max_length=200, null=True)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_termino', models.DateField(blank=True, null=True)),
                ('prescrito_por', models.CharField(blank=True, max_length=200, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to='core.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='SinalVital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('temperatura', models.FloatField(blank=True, null=True)),
                ('pressao_arterial', models.CharField(blank=True, max_length=20, null=True)),
                ('frequencia_cardiaca', models.IntegerField(blank=True, null=True)),
                ('frequencia_respiratoria', models.IntegerField(blank=True, null=True)),
                ('saturacao_oxigenio', models.FloatField(blank=True, null=True)),
                ('glicemia', models.FloatField(blank=True, null=True)),
                ('dor_escala', models.IntegerField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sinais', to='core.paciente')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
