# Generated by Django 6.0.1 on 2026-01-28 01:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='condicoes_cronicas',
            new_name='comorbidades',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='entrada_ilpi',
            new_name='data_entrada',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='contato_emergencia',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='telefone_emergencia',
        ),
        migrations.AddField(
            model_name='paciente',
            name='possui_alergia',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Prescricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_medicamento', models.CharField(max_length=120)),
                ('dosagem', models.CharField(blank=True, max_length=60, null=True)),
                ('via', models.CharField(blank=True, max_length=40, null=True)),
                ('frequencia', models.CharField(blank=True, max_length=40, null=True)),
                ('horarios', models.CharField(blank=True, max_length=120, null=True)),
                ('ativa', models.BooleanField(default=True)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_termino', models.DateField(blank=True, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='AdministracaoDose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('administrado', models.BooleanField(default=False)),
                ('administrado_em', models.DateTimeField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('administrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('prescricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.prescricao')),
            ],
            options={
                'unique_together': {('prescricao', 'data', 'horario')},
            },
        ),
    ]
