# Generated by Django 6.0.1 on 2026-01-28 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_condicoes_cronicas_paciente_comorbidades_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('MED', 'Medicamento'), ('FRA', 'Fralda')], max_length=3)),
                ('unidade', models.CharField(default='un', max_length=30)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='comorbidades',
            new_name='condicoes_cronicas',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='data_entrada',
            new_name='entrada_ilpi',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='possui_alergia',
        ),
        migrations.AddField(
            model_name='paciente',
            name='contato_emergencia',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='telefone_emergencia',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='EstoquePacienteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_atual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('minimo_alerta', models.DecimalField(decimal_places=2, default=10, max_digits=10)),
                ('consumo_diario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoques', to='core.paciente')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.produto')),
            ],
            options={
                'unique_together': {('paciente', 'produto')},
            },
        ),
        migrations.CreateModel(
            name='MovimentoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('DOSE', 'Administração de Dose'), ('FRALDA', 'Consumo Diário de Fraldas'), ('AJUSTE', 'Ajuste Manual')], max_length=10)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentos', to='core.estoquepacienteitem')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
