# Generated by Django 6.0.1 on 2026-01-28 20:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_produto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstoqueFralda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='G', max_length=60)),
                ('quantidade_atual', models.IntegerField(default=0)),
                ('consumo_dia', models.IntegerField(default=6)),
                ('alerta_minimo', models.IntegerField(default=20)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoque_fraldas', to='core.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='EstoqueMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_medicamento', models.CharField(max_length=200)),
                ('quantidade_atual', models.IntegerField(default=0)),
                ('unidade', models.CharField(default='un', max_length=30)),
                ('alerta_minimo', models.IntegerField(default=5)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoque_medicamentos', to='core.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='MovEstoqueFralda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=10)),
                ('quantidade', models.IntegerField()),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('observacao', models.CharField(blank=True, max_length=200, null=True)),
                ('estoque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movs', to='core.estoquefralda')),
            ],
        ),
        migrations.CreateModel(
            name='MovEstoqueMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=10)),
                ('quantidade', models.IntegerField()),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('observacao', models.CharField(blank=True, max_length=200, null=True)),
                ('estoque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movs', to='core.estoquemedicamento')),
            ],
        ),
    ]
