# Generated by Django 6.0.1 on 2026-01-28 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_estoquefralda_estoquemedicamento_movestoquefralda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='casa',
            field=models.CharField(choices=[('Casa 1', 'Casa 1'), ('Casa 2', 'Casa 2')], default='Casa 1', max_length=20),
        ),
    ]
